'''
    Here is the code to transform the body points to a points that can be
    interpreted by the blender script
    For instance, this code can transform the text file in the body folder to final_body folder,
    where in final_body folder, blender can interpret it.
    The reason why we have body folder is because those points are generated by pipeMedia
    8/19/2022 Saliteta
'''
import os

SOURCE_FOLDER = 'body/'
TEMP_FOLDER = 'temp_body/'
OUTPUT_FOLDER = 'final_body/'

if not os.path.exists(SOURCE_FOLDER[:-1]):
    print('source folder does not exist')
    exit()

if not os.path.exists(TEMP_FOLDER[:-1]):
    os.makedirs(TEMP_FOLDER[:-1])
    print('create temp folder')

if not os.path.exists(OUTPUT_FOLDER[:-1]):
    os.makedirs(OUTPUT_FOLDER[:-1])
    print('create output folder')


for i in range(303):
    buffer = []
    a = str(i).zfill(5)
    with open(SOURCE_FOLDER+a+".txt") as file:
        buffer = file.readlines()
    #for j in range(len(buffer)):
    #    buffer[j] = buffer[j].replace(" ","")
        # since we some time have multiple space
    buffer[32] = '       '+buffer[32].split('joint')[-1][1:]
    buffer[-1] = buffer[-1].split(')')[0][:-1]
    file = open(TEMP_FOLDER+str(i)+".txt", 'w')
    file.writelines(buffer[43:57])
    file.close()




for i in range(303):
    buffer = []
    with open(TEMP_FOLDER+str(i)+".txt") as file:
        buffer = file.readlines()
    for j in range (len(buffer)):
        buffer[j] = buffer[j].replace('[','[ ')
        buffer[j] = buffer[j].replace(']',' ]')
    #buffer[-1] = buffer[-1].split(')')[0][:-1]
    file = open(OUTPUT_FOLDER+str(i)+".txt", 'w')
    file.writelines(buffer)
    file.close()



