name: mp
channels:
  - defaults
  - conda-forge
  - open3d-admin
dependencies:
  - pip=21.1.2
  - python=3.8.10
  - numpy=1.20.3
  - pip:
    - open3d==0.12.0
    - mediapipe==0.8.9.1
    - opencv-python==4.5.2.54
    - opencv-contrib-python==4.5.2.54